version: 2
jobs:
    test_frontend:
        docker:
            - image: circleci/node
    steps:
        - checkout
        - run: yarn install
        - run: yarn test
workflows:
    version: 2
    run_test:
        jobs:
            - test_frontend